model_name: classifier                        # model name

dataset: dogs                                 # dataset (STL10, dogs, CIFAR10 supported)

###### Train Settings ######
train:
  freeze: false                               # whether to freeze backbone layers
  batch_size: 32                              # batch size
  epochs: 100                                 # training epochs
  loss: xent                                  # training loss (xent only supported)

###### Augmentations ######
transform: 
  img_size: 96                                # input image size: 
  mean: [0.485, 0.456, 0.406]                 # ImageNet mean normalization ([0.485, 0.456, 0.406])
  std: [0.229, 0.224, 0.225]                  # ImageNet std normalization ([0.229, 0.224, 0.225])

###### Optimizer ######
optimizer:
  algo: sgd                                   # optimization algorithm (adam, sgd)
  lr: 0.002                                   # learning rate
  weight_decay: 1.5e-6                        # weight decay                     
  momentum: 0.9                               # SGD momentum

###### Scheduler ######
scheduler:
  algo: cosine                                # scheduler algorithm (cosine and linear supported)
  cosine:                                     # cosine params
    T_max: 50                                 # maximum iterations for scheduler
    eta_min: 0.00002                          # minimum learning rate
    verbose: true
  linear:
    start_factor: 0.8                         # linear scaling factor at each iter
    end_factor: 1.0                           # the number we multiply learning rate at the end of linear changing process
    total_iters: 10                           # number of epochs for applying linear lr scherduling
    verbose: true