model_name: byol                              # model name

dataset: Tennis                                # dataset to use among STL10, etc.

model:
  backbone: resnet18                          # model to use as feature extractor
  hidden_size: 4096                           # MLP predictor hidden units
  projection_size: 256                        # MLP output size

train:
  epochs: 50                                  # training epochs
  batch_size: 64                              # batch size
  
optimizer:
  algo: adam                                  # optimization algorithm
  lr: 0.0001                                  # learning rate
  weight_decay: 0.0000001                     # weight decay                     

loss:
  type: norm_mse                              # loss 

transform: 
  img_size: 96                                # input image size
  mean: [0.485, 0.456, 0.406]                 # ImageNet mean normalization
  std: [0.229, 0.224, 0.225]                  # ImageNet std normalization
  brightness: 0.8                             # color jitter brightness
  contrast: 0.8                               # color jitter contrast
  saturation: 0.8                             # color jitter saturation
  hue: 0.2                                    # color jitter hue            
  color_jitter_p: 0.5                         # color jitter transformation probability
  grayscale_p: 0.2                            # grayscale transformation probabilty
  h_flip_p: 0.5                               # horizontal flip transformation probabilty
  kernel: [3, 3]                              # gaussian blur kernel size
  sigma: [.1, 2]                             # gaussian blur params
  gaussian_blur_p: 0.1                        # gaussian blur transformation probability

scheduler:
  algo: cosine
  cosine:
    T_max: 50
    eta_min: 0.00005
    verbose: true




