model_name: classifier                        # model name

dataset: dogs                                # dataset to use among STL10, dogs, CIFAR10.

model:
  freeze: false                               # whether to freeze ssl backbone layers

train:
  batch_size: 32
  epochs: 10
  loss: xent

transform: 
  img_size: 96                                # input image size: 
  mean: [0.485, 0.456, 0.406]                 # ImageNet mean normalization ([0.485, 0.456, 0.406])
  std: [0.229, 0.224, 0.225]                  # ImageNet std normalization ([0.229, 0.224, 0.225])

optimizer:
  algo: adam                                  # optimization algorithm
  lr: 0.002                                    # learning rate
  weight_decay: 1.5e-6                        # weight decay                     

scheduler:
  algo: cosine                                # scheduler algorithm    
  cosine:                                     # cosine params
    T_max: 100                                # maximum iterations for scheduler
    eta_min: 0.00002                          # minimum learning rate
    verbose: true